services:
  wordpress:
    image: wordpress:v1
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /srv/data/wordpress:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped
  nginx:
    image: nginx:v1
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - /srv/data/wordpress:/var/www/html:ro
    networks:
      - inception_network
    restart: unless-stopped
  mariadb:
    image: mariadb:v1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /srv/data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
      
networks:
  inception_network:
    driver: bridge
