services:
  wordpress:
    image: wordpress:v1
    depends_on:
      - mariadb
      - nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  nginx:
    image: nginx:v1
    depends_on:
      - mariadb
    ports:
      - 443:433
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  mariadb:
    image: mariadb:v1
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
volumes:
  wordpress_data:
  mariadb_data:
      
networks:
  inception_network:
    driver: bridge
